### PR TITLE
Add speed to the ball on a certain interval ⚾️ / Added comments for newcomers 💬

### PR DESCRIPTION
**Pull request by pierreericgarcia**
_This pull request addresses issue #6_ 

# Introducing 3 new variables 😄

```
// Store the last level update in a variable
var changedLevelAt = Date.now();
const SECOND = 1000;
// Setting the interval by which the speed will increase
var timeInterval = 5 * SECOND;
// Speed added to the ball at each interval
var speedAdded = 2;
```

## 1. changedLevelAt ⌛️ 

This variable contains a timestamp which point to the last time the ball speed has increased. By this way we can track easily when will the next update will take place.

## 2. timeInterval ⏲ 

This variable allow us to tell at which interval we want the ball speed to update. Adding it to the changedLevelAt variable will get us the next speed update date. By this way we can easily update the speed depending on the current timestamp.

```
if (Date.now() > (changedLevelAt + timeInterval)) {
	// Increase the ball speed and update changedLevelAt
	changedLevelAt = Date.now();
}
```

## 3. speedAdded 🐎 

Easy at it sounds ! This variable lets you set the speed added to the ball when the level change.

# The main mechanism ⚙️

The main mechanism by which the speed update is in the first if statement of the moveEverything function.

```
if (Date.now() > (changedLevelAt + timeInterval)) {
	if (ballSpeedX < 0) {
		ballSpeedX -= speedAdded;
	} else {
		ballSpeedX += speedAdded;
	}

	if (ballSpeedY < 0) {
		ballSpeedY -= speedAdded;
	} else {
		ballSpeedY += speedAdded;
	}

	changedLevelAt = Date.now();
}
```

Depending on the current direction of the ball, the ball speed will update negatively or positively.

# Comments 💬 

I also added comments to the main.js file. It's always easier for newcomers to read the comments indeed of understanding the code mechanisms. But feel free to delete it 😄 .

Thank you for reading this ! 👍

### CODE REVIEW

**Review by amitsagtani97 — CHANGES_REQUESTED** [review]
@Dokeezy The ball is not following the normal physics. When we hit the ball with player paddle and as soon as it covers half of the path it bends in a straight path. Can you please check it?

**Comment by pierreericgarcia** [comment]
@amitsagtani97 I updated the if statements where the speed values were changing. Now I also check if the Y value is negative or not and update it accordingly. I hope you'll like this fix 😄

**Comment by amitsagtani97** [comment]
@Dokeezy Thanks for the PR :) :+1:

**Comment by pierreericgarcia** [comment]
@amitsagtani97 Thank you very much for accepting it ! 😁 To be honest it's my first one, I'm kind of glad 😂

**Pull request merged**
